name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ''
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            ext: '.exe'
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            ext: ''
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            ext: ''

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o factctl${{ matrix.ext }} cmd/factctl/main.go
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: factctl-${{ matrix.goos }}-${{ matrix.goarch }}
        path: factctl${{ matrix.ext }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux-amd64/factctl
          windows-amd64/factctl.exe
          darwin-amd64/factctl
          linux-arm64/factctl
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

