name: Build and Release

on:
  release:
    types: [published]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ''
          - os: ubuntu-latest
            goos: windows
            goarch: amd64
            ext: '.exe'
          - os: ubuntu-latest
            goos: darwin
            goarch: amd64
            ext: ''
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            ext: ''

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o factctl${{ matrix.ext }} cmd/factctl/main.go
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: factctl-${{ matrix.goos }}-${{ matrix.goarch }}
        path: factctl${{ matrix.ext }}

  upload:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          factctl-linux-amd64/factctl
          factctl-windows-amd64/factctl.exe
          factctl-darwin-amd64/factctl
          factctl-linux-arm64/factctl
        tag_name: ${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


